#	author: "Finnian Reilly"
#	copyright: "Copyright (c) 2017 Finnian Reilly"
#	contact: "finnian at eiffel hyphen loop dot com"
#	license: "MIT license (See: en.wikipedia.org/wiki/MIT_License)"
#	date: "20 July 2017"

import os, sys, platform
from os import path

from eiffel_loop.scons import util
from eiffel_loop.eiffel import project


if platform.system () == "Windows":
	print "Not yet implemented on Windows"
	Exit(1);
	
else:
	is_unix = True
	compiler_flags = ['-g', '-O3', '-mpopcnt']

env = Environment (CCFLAGS = compiler_flags, ENV = os.environ)

build_dir =  project.platform_spec_build_dir ()

VariantDir (build_dir, 'source', duplicate=0)

sources = Glob (path.join (build_dir, '*.c'))
lib = env.StaticLibrary (path.join (build_dir, 'pf_bit_utils'), sources)
	
env.NoClean (lib)
#Return ('lib')
