// Generated by SCons
// Do not edit

/* Define to 1 if you have the 'getopt_long' function.*/
#define HAVE_GETOPT_LONG 1

/* Define to 1 if you have the 'mkstemp' function.*/
#define HAVE_MKSTEMP 1

/* Define to 1 if you have the 'truncate' function.*/
#define HAVE_TRUNCATE 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES 1

/* Define to 1 if you have the <libcw/sys.h> header file. */
/* #undef HAVE_LIBCW_SYS */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB 1

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD 1

/* Define to 1 if you have the <wchar.h> header file. */
#define HAVE_WCHAR 1

/* Define to 1 if you have the <zlib.h> header file. */
#define HAVE_ZLIB 1

/* Define to 1 if you have the <bitset> header file. */
#define HAVE_BITSET 1

/* Define to 1 if you have the <cctype> header file. */
#define HAVE_CCTYPE 1

/* Define to 1 if you have the <climits> header file. */
#define HAVE_CLIMITS 1

/* Define to 1 if you have the <cstdio> header file. */
#define HAVE_CSTDIO 1

/* Define to 1 if you have the <cstdlib> header file. */
#define HAVE_CSTDLIB 1

/* Define to 1 if you have the <cstring> header file. */
#define HAVE_CSTRING 1

/* Define to 1 if you have the <fstream> header file. */
#define HAVE_FSTREAM 1

/* Define to 1 if you have the <fstream.h> header file. */
/* #undef HAVE_FSTREAM */

/* Define to 1 if you have the <iomanip> header file. */
#define HAVE_IOMANIP 1

/* Define to 1 if you have the <iomanip.h> header file. */
/* #undef HAVE_IOMANIP */

/* Define to 1 if you have the <iostream> header file. */
#define HAVE_IOSTREAM 1

/* Define to 1 if you have the <iostream.h> header file. */
/* #undef HAVE_IOSTREAM */

/* Define to 1 if you have the <string> header file. */
#define HAVE_STRING 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING 1

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

#define VERSION "3.8.3"

#define _ID3LIB_NAME "id3lib"

#define _ID3LIB_VERSION "3.8.3"

#define _ID3_COMPILED_WITH_DEBUGGING "minimum"

#define _ID3LIB_FULLNAME "id3lib-3.8.3"

#define _ID3LIB_MAJOR_VERSION 3

#define _ID3LIB_MINOR_VERSION 8

#define _ID3LIB_PATCH_VERSION 4

#define _ID3LIB_INTERFACE_AGE 0

#define _ID3LIB_BINARY_AGE 0


/* Define if you need to in order for stat and other things to work. */
/* #undef _POSIX_SOURCE */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */
/* This is the bottom section */

#if defined (ID3_ENABLE_DEBUG) && defined (HAVE_LIBCW_SYS_H) && defined (__cplusplus)

#define DEBUG

#include <libcw/sys.h>
#include <libcw/debug.h>

#define ID3D_INIT_DOUT()    Debug( libcw_do.on() )
#define ID3D_INIT_WARNING() Debug( dc::warning.on() )
#define ID3D_INIT_NOTICE()  Debug( dc::notice.on() )
#define ID3D_NOTICE(x)      Dout( dc::notice, x )
#define ID3D_WARNING(x)     Dout( dc::warning, x )

#else

#  define ID3D_INIT_DOUT()
#  define ID3D_INIT_WARNING()
#  define ID3D_INIT_NOTICE()
#  define ID3D_NOTICE(x)
#  define ID3D_WARNING(x)

#endif /* defined (ID3_ENABLE_DEBUG) && defined (HAVE_LIBCW_SYS_H) */

