// Generated by SCons
// Do not edit

/* Define to 1 if you have the <assert.h> header file. */
#define HAVE_ASSERT 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD 1

/* Define to the name of package */
#define PACKAGE "libid3tag"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "support@underbit.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "ID3 Tag"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "ID3 Tag 0.15.1b"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libid3tag"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.15.1b"

/* Define to the Version number of package */
#define VERSION "0.15.1b"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

