# 	Port of libid3tag autoconf configuration to Scons
#
#	author: "Finnian Reilly"
#	copyright: "Copyright (c) 2001-2010 Finnian Reilly"
#	contact: "finnian at eiffel hyphen loop dot com"
#	license: "MIT license (See: en.wikipedia.org/wiki/MIT_License)"
#	date: "7 Jan 2010"
#	revision: "0.1"

import os

from os import path

from eiffel_loop.eiffel import project

if os.name == "nt":
	compiler_flags = ['-Ox', '-Zi', '-c', '-MT', '-w', '-nologo', '-DEIF_THREADS']
	include_path = ["include", path.expandvars (path.normpath ("$ISE_EIFFEL/studio/spec/$ISE_PLATFORM/include"))]
	
	env = Environment(
		CCFLAGS = compiler_flags, CPPPATH = include_path, ENV = os.environ, ISE_EIFFEL = os.environ ['ISE_EIFFEL']
	)

	build_dir = project.platform_spec_build_dir ()

	VariantDir (build_dir, 'source', duplicate=0)

	library_path = path.join (build_dir, 'wex_mci')

	lib = env.StaticLibrary (library_path, [path.join (build_dir, 'cwex.cpp')])

	env.NoClean (lib)
